version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: 'shopdevgo'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  redis:
    image: redis:latest
    container_name: redis_server
    command: redis-server --databases 1
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  redis_data:
