version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: 'shopdevgo'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
