server:
  port: 8082
  host: localhost
  mode: dev
mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifetime: 3600
logger:
  level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 10
  max_backups: 3
  max_age: 7
  compress: true
redis:
  host: localhost
  port: 6381
  password: ""
  db: 0
